spring.application.name=seat-reservation

spring.datasource.url=jdbc:postgresql://localhost:5432/seat_reservation
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true

server.port=8080